### ISSUE TITLE
Incorrect gif in comment

### ISSUE THREAD

**Issue by mras2303** [micnncim/action-lgtm-reaction#37]
`![](https://media.giphy.com/media/&{gif N0m8shgMRLbag https://giphy.com/gifs/black-and-white-thumbs-up-edward-cullen-N0m8shgMRLbag black and white yes GIF}/giphy.gif)`

This is what I got after comment. It looks like wrong configuration in your script. I tried to convert it into Javascript, but unfortunately I don't know Golang 

Did I wrong something?
My configuration of action:

```yaml
name: Send LGTM reaction
on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: micnncim/action-lgtm-reaction@v0.5.7
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ISSUE_NUMBER: ${{ github.event.issue.number }}
          GITHUB_COMMENT_BODY: ${{ github.event.comment.body }}
          GITHUB_COMMENT_ID: ${{ github.event.comment.id }}
          GITHUB_PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REVIEW_BODY: ${{ github.event.review.body }}
          GITHUB_REVIEW_ID: ${{ github.event.review.id }}
        with:
          trigger: '[".*looks good to me.*"]'
          override: true
          source: 'giphy'
```
