### ISSUE TITLE
"Nerdy Integration" gives me the error `no giphy`

### ISSUE THREAD

**Issue by Blackjacx** [micnncim/action-lgtm-reaction#44]
When I the action the nerdy way I dont get any gif :-( This is my workflow:
```
name: LGTM

on:
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: micnncim/action-lgtm-reaction@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
        with:
          trigger: '[".*looks good to me.*", "^lgtm$", "^[gG]ood [jJ]ob!?$"]'
          override: true
          source: 'giphy'
```
